```{r include=FALSE}
# This is the template for the tabsets of each main heading
# It expects these variables in the environment:
# nrows - number of rows in the faceted plots
# linear_plot, log_plot, growth_plot, total_plot
# Optional:
# daily_plot, nrows_daily, new_vs_all_plot
```

#### {.tabset}

##### Selected {.tabset}

###### Linear

```{r fig.height=6, fig.width=8}
print(linear_plot)
```

###### Log

```{r fig.height=6, fig.width=8}
print(log_plot)
```

```{r fig.height=6, fig.width=8, results='asis'}
if (exists('daily_by_date') && !is.null(daily_by_date)) {
  cat('\n\n###### By date\n\n')
  print(daily_by_date)
}
```

```{r fig.height=nrows_daily*2.2+0.5, results='asis'}
if (!is.null(daily_plot)) {
  cat('\n\n##### Daily\n\n')
  print(daily_plot)
}

# if (!is.null(new_vs_all_plot)) {
#   cat('\n\n##### New vs All\n\n')
#   print(new_vs_all_plot)
# }

```

```{r fig.height=nrows*2.2+0.5, results='asis'}
if (!is.null(growth_plot)) {
  cat('\n\n##### Growth\n\n')
  print(growth_plot)
}
```

```{r fig.height=nrows*1.2+0.5, results='asis'}
if (!is.null(growth_plot)) {
  cat('\n\n##### Totals\n\n')
  print(total_plot)
}
```
